apiVersion: v1
kind: Pod
metadata:
  name: flask
  namespace: skaffold
  labels:
    app.kubernetes.io/name: flask
spec:
  containers:
    - name: flask
      image: flask
      ports:
        - containerPort: 5000
          name: http-flask
---
apiVersion: v1
kind: Pod
metadata:
  name: flask-db
  namespace: skaffold
  labels:
    app.kubernetes.io/name: flask-db
spec:
  containers:
    - name: flask-db
      image: mongo:6.0.2
      ports:
        - containerPort: 27017
          name: mongodb
  # portForward:
  #   - resourceType: pod
  #     resourceName: flask
  #     namespace: skaffold
  #     port: 5000
  #     localPort: 5000 # *Optional*
