apiVersion: v1
kind: Service
metadata:
  name: flask
  namespace: skaffold
spec:
  selector:
    app.kubernetes.io/name: flask
  ports:
    - name: http-flask
      protocol: TCP
      port: 5000
      targetPort: http-flask
---
apiVersion: v1
kind: Service
metadata:
  name: flask-db
  namespace: skaffold
spec:
  selector:
    app.kubernetes.io/name: flask-db
  ports:
    - name: mongodb
      protocol: TCP
      port: 27017
      targetPort: mongodb
